title: Komputasi Geoteknik
description: Komputasi Geoteknik UNS
sitename: Komputasi Geoteknik
baseurl: '/komputasi-geoteknik'
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
